version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    container_name: elasticsearch-7.17.7
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - ./es-data:/var/lib/elasticsearch/data      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.7
    container_name: kibana-7.17.7
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.7
    container_name: filebeat-7.17.7
    volumes:
      - ./fs-logs/conf/filebeat.yml:/etc/filebeat/filebeat.yml
      - ./fs-logs/log/inputlog:/var/log/fb-logs
      - ./fs-logs/log/filebeat:/var/log/filebeat
    environment:
      - ELASTICSEARCH_HOSTS="elasticsearch:9200"
