filebeat.inputs:
- type: log
  paths:
    - /usr/share/filebeat/logs/sample.log

setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"

output.elasticsearch:
  hosts: ["http://elasicsearch:9200"]
  index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
